services:
  app:
    build:
      context: .
      target: production
    command: npm run start
    env_file:
      - .env.production
    ports:
      - "${PORT:-3000}:3000"
    restart: unless-stopped
